name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15  # GitHub macOS runner with latest Xcode (15.x or 16.x)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          xcodebuild -version

      - name: Resolve Swift Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies \
            -project "Cal AI.xcodeproj"

      - name: Build iOS app
        run: |
          xcodebuild -project "Cal AI.xcodeproj" \
            -scheme "Cal AI" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest" \
            clean build
